[package]
name = "ollama-file-find"
version = "0.1.0"
edition = "2024"

[dependencies]
ollama-file-find-inner = { path = "src/ollama-file-find-inner" }
anyhow = "1.0.99"
serde_json = "1.0"
clap = { version = "4.5", features = ["derive"] }
