[package]
name = "ollama-file-find"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
dirs = "6.0.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0"
walkdir = "2.5.0"